// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_SqadQGxFdblyq1mrFhxm3tNRnsk1Kd4',
    appId: '1:784211428545:web:16441c5f2d4a6e323a0040',
    messagingSenderId: '784211428545',
    projectId: 'quiz-app-311c1',
    authDomain: 'quiz-app-311c1.firebaseapp.com',
    storageBucket: 'quiz-app-311c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8GTUccCpkLYGsjBgRux8gLdUMmluAaLg',
    appId: '1:784211428545:android:1b96187f5033f3c03a0040',
    messagingSenderId: '784211428545',
    projectId: 'quiz-app-311c1',
    storageBucket: 'quiz-app-311c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqgMk7jEYej4zryuM-apwI34mgVDK-EQ',
    appId: '1:784211428545:ios:28947369273ee9383a0040',
    messagingSenderId: '784211428545',
    projectId: 'quiz-app-311c1',
    storageBucket: 'quiz-app-311c1.appspot.com',
    iosClientId: '784211428545-ihg5branmvpbhid043vljugjgbtoddua.apps.googleusercontent.com',
    iosBundleId: 'com.arif.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqgMk7jEYej4zryuM-apwI34mgVDK-EQ',
    appId: '1:784211428545:ios:28947369273ee9383a0040',
    messagingSenderId: '784211428545',
    projectId: 'quiz-app-311c1',
    storageBucket: 'quiz-app-311c1.appspot.com',
    iosClientId: '784211428545-ihg5branmvpbhid043vljugjgbtoddua.apps.googleusercontent.com',
    iosBundleId: 'com.arif.quizapp',
  );
}
